# Generated by Django 3.0.5 on 2021-07-06 15:18

from django.db import migrations
from django.db import connection, IntegrityError
from psycopg2 import errors


def assign_birthday(date, first_tracker_number, last_tracker_number, tracker_group):
  for x in range(first_tracker_number, last_tracker_number+1, 1):
    found_id = None

    try:
      cursor = connection.cursor()
      cursor.execute(f"select id from unit_logs_tracker where number = {x} and tracker_group = '{tracker_group}'")
      found_id = cursor.fetchone()[0]
    except:
      continue

    exp = f"insert into unit_logs_entry (timestamp, tracker_id, status_id, comments) select TO_TIMESTAMP('{date} 01:00:00+00', 'YYYY-MM-DD HH:MI:SS'), {found_id}, 1, ''"
    cursor.execute(exp)


class Migration(migrations.Migration):

    dependencies = [
      ('unit_logs', '0012_auto_20210709_1505'),
    ]

    def forwards(apps, schema_editor):
      assign_birthday('2020-11-01', 1,40, 'Other')
      assign_birthday('2019-09-12', 97,98, 'Enable')

    operations = [
      migrations.RunPython(forwards)
    ]
